---
title: My Awesome Site
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write a short description here.
baseurl: ""
url: "http://yourdomain.com"
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-sitemap

